### ISSUE TITLE
SparkFun Thing Plus not showing up in platformio

### ISSUE THREAD

**Issue by drewfish** [sparkfun/Arduino_Boards#64] opened 2020-04-21 15:29 UTC
I don't seem to be able to find the [SparkFun Thing Plus](https://www.sparkfun.com/products/14713) in the platformio board registry.

I've done `pio platform install atmelsam --with-package framework-arduino-samd-sparkfun` (installed version 1.7.4) but afterwards `platformio boards | grep sparkfun_thing` only shows the `sparkfun_thing_plus_v` (which doesn't use the SAMD51 chip apparently). The Platformio [online board registry](https://platformio.org/boards) doesn't seem to show the Thing Plus either.

Is there some part of the platformio ecosystem that needs to be rebuilt to pick up the board definitions in this repo?

**Comment by drewfish** [comment] 2020-04-21 20:05
Oh hmm... it looks like the list of boards in platformio might be coming from this:
https://github.com/platformio/platform-atmelsam/tree/develop/boards

**Comment by drewfish** [comment] 2020-04-22 00:26
I've opened an issue on one of the platformio repos:
https://github.com/platformio/platform-atmelsam/issues/106

**Comment by santaimpersonator** [comment] 2020-10-08 20:28
I will be closing this issue. There doesn't seem to be an issue with our Arduino core, since the problem is being experienced on a completely different development platform.

**Closed by santaimpersonator** 2020-10-08 20:28 UTC
Labels: invalid, wontfix
